pub(crate) const DEFAULT_PROFILE_ID:&str = "DEFAULT_PROFILE_ID";
pub(crate) const DEFAULT_PROFILE_TITLE:&str = "DEFAULT_PROFILE_TITLE";
pub(crate) const DEFAULT_PROFILE_PROCESS_NAME:&str = "DEFAULT_PROFILE_PROCESS_NAME";



crate::create_profile!(DEFAULT_PROFILE_ID, DEFAULT_PROFILE_TITLE, DEFAULT_PROFILE_PROCESS_NAME, |profile| profile);